export const QUOTES = [
  "The way to get started is to quit talking and begin doing.",
  "Don't let yesterday take up too much of today.",
  "Action is the foundational key to all success.",
  "Your mind is for having ideas, not holding them.",
  "Focus on being productive instead of busy.",
  "The best way to predict the future is to create it.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "What you do today can improve all your tomorrows.",
  "Do one thing every day that gives you peace of mind.",
  "Small daily improvements lead to stunning results.",
  "Your limitation is only your mind.",
  "Dream big. Start small. Act now.",
  "The secret of getting ahead is getting started.",
  "Make each day a masterpiece.",
  "Progress, not perfection.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Success is where preparation and opportunity meet.",
  "Don't watch the clock; do what it does and keep going.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "Your work will come alive when you do.",
  "Quality means doing it right when no one is looking.",
  "The hardest battle is fighting against laziness.",
  "One hour of work produces many of the best results.",
];
