export const QUOTES = [
  "The way to get started is to quit talking and begin doing.",
  "Don't let yesterday take up too much of today.",
  "Action is the foundational key to all success.",
  "Your mind is for having ideas, not holding them.",
  "Focus on being productive instead of busy.",
  "The best way to predict the future is to create it.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "What you do today can improve all your tomorrows.",
  "Do one thing every day that gives you peace of mind.",
  "Small daily improvements lead to stunning results.",
  "Your limitation is only your mind.",
  "Dream big. Start small. Act now.",
  "The secret of getting ahead is getting started.",
  "Make each day a masterpiece.",
  "Progress, not perfection.",
];
